### ISSUE TITLE
Cannot use `/env` as a kubernetes secret mountPath

### ISSUE THREAD

**Issue by tym-xqo** [OAODEV/config-finder#9]
Third spot checked in `finders.py` is "some line in the file at /env" However, it seems to be impossible to mount a kubernetes secret at the filesystem root. For example, trying to create a pod like:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: secret-test
  name: secret-test
spec:
  containers:
  - image: alpine
    name: secret-test
    command:
        - "tail"
        - "-f"
        - "/dev/null"
    ports:
    - containerPort: 22
    volumeMounts:
    - mountPath: /
      name: env
  volumes:
  - name: env
    secret:
      secretName: test-secret
```

Leaves the pod in RunContainerError status, with the error message

> Error syncing pod, skipping: failed to "StartContainer" for "secret-test" with RunContainerError: "runContainer: Error response from daemon: Invalid bind mount spec \"/var/lib/kubelet/pods/03ea2d38-63d8-11e6-8479-ae880d866a65/volumes/kubernetes.io~secret/env:/\": **Invalid specification: destination can't be '/'** in '/var/lib/kubelet/pods/03ea2d38-63d8-11e6-8479-ae880d866a65/volumes/kubernetes.io~secret/env:/'

If you change the `spec.volumeMounts.mountPath` in the above YAML to (say) `/secret` then it works as expected, although the config-finder would need to check /secret/env for config instead of /env
